const copy={en:{eyebrow:'A PHYSICS COLLECTION',title:'Physics Theory Club',sub:'Exposition of Special Relativity',intro:'Explore the principles that shape our understanding of space, time and motion.',topics:['Special Relativity','Classical Mechanics','Electrodynamics','Orbital Mechanics','Classical Field Theory'],enter:'Explore ↗',soon:'Coming soon',back:'← All physics topics',section:'Special Relativity',pending:'Derivations coming soon.',footer:'SPACE · TIME · MOTION',titles:['Derivation of Lorentz Transformation','Relativistic Kinematics','Linear Acceleration in Special Relativity','Proof of p = γmv by the Stationary-action Principle'],alt:['Parallel spatial coordinate systems in relative motion','Two balls approaching at 0.8c each, relative speed 0.9756c','Spacecraft accelerating away from Earth','Faint portraits of Henri Poincaré and Lev Landau']},zh:{eyebrow:'物理专题',title:'Physics Theory Club',sub:'狭义相对论专题展',intro:'探索空间、时间与运动背后的物理原理。',topics:['狭义相对论','经典力学','电动力学','轨道力学','经典场论'],enter:'进入专题 ↗',soon:'敬请期待',back:'← 全部物理主题',section:'狭义相对论',pending:'详细推导即将开放。',footer:'空间 · 时间 · 运动',titles:['洛伦兹变换的推导','相对论运动学','狭义相对论中的直线加速运动','利用驻作用量原理证明 p = γmv'],alt:['两个相对运动的平行空间坐标系','两个小球各以0.8c相向运动，相对速率0.9756c','飞船以恒定固有加速度飞离地球','淡色的庞加莱与朗道肖像']}};
let lang='en';try{lang=localStorage.getItem('physics-language')==='zh'?'zh':'en'}catch{}
let selected=null;
const main=document.querySelector('main'),dialog=document.querySelector('dialog');
const frac=(a,b)=>`<span class="fraction"><span>${a}</span><span>${b}</span></span>`;
const formulas=[`<span class="matrix vector"><span>x′</span><span>t′</span></span> = γ <span class="matrix"><span>1</span><span>−v</span><span>−v/c²</span><span>1</span></span><span class="matrix vector"><span>x</span><span>t</span></span>`,`v<sub>ac</sub> = ${frac('v<sub>ab</sub> + v<sub>bc</sub>','1 + v<sub>ab</sub>v<sub>bc</sub>/c²')}`,'',`S = ∫ α dτ &nbsp;&nbsp; H = γmc²`];

function accelerationFormula(){const zh=lang==='zh';return '<div class="acceleration-formulas"><div><span class="frame-label">'+(zh?'地球参考系 · 飞船的速度':'Earth frame · spacecraft velocity')+'</span><span class="equation">v(t) = '+frac('at','√(1 + (at/c)²)')+'</span></div><div><span class="frame-label">'+(zh?'飞船瞬时共动系 · 地球的速度':'Instantaneous ship frame · Earth velocity')+'</span><span class="equation">u′<sub>E</sub>(τ) = −c tanh(aτ/c)</span></div><p class="formula-note">'+(zh?'初始相对静止；a 为恒定固有加速度。<br>t：地球时间 · τ：飞船固有时间':'Initially at rest together; constant proper acceleration a.<br>t: Earth time · τ: spacecraft proper time')+'</p></div>'}
function formula(i){return i===2?accelerationFormula():'<span class="equation">'+formulas[i]+'</span>'}
function diagram(i){
 const t=copy[lang];
 if(i===3)return '<div class="diagram portraits"><img src="assets/poincare-landau.png" alt="'+t.alt[i]+'"><div class="portrait-names"><span>Henri Poincaré</span><span>Lev Landau</span></div></div>';
 const drawings=[
 '<g fill="none" stroke-width="1.7"><path d="M74 142H214M88 155V35" stroke="#9bb4d2"/><path d="M260 142H407M278 155V35" stroke="#acd4ff"/><path d="M205 67H251M245 61L251 67L245 73" stroke="#acd4ff"/></g><text x="218" y="146">x</text><text x="72" y="29">y</text><text x="412" y="146">x′</text><text x="260" y="29">y′</text><text x="74" y="171">O</text><text x="263" y="171">O′</text><text x="137" y="107" font-size="23">S</text><text x="328" y="107" font-size="23">S′</text><text x="225" y="54">v</text>',
 '<path d="M100 82V49H390V82" stroke="#779ecb" stroke-width="1.6" fill="none"/><rect x="160" y="30" width="170" height="35" rx="5" fill="#15263d"/><text x="245" y="53" text-anchor="middle" fill="#c8e5ff" font-size="22">0.9756c</text><circle cx="100" cy="121" r="17" fill="#a6cfff"/><circle cx="390" cy="121" r="17" fill="#83acd9"/><g stroke="#b8d9ff" stroke-width="2" fill="none"><path d="M133 121H204L195 114M204 121L195 128M357 121H286L295 114M286 121L295 128"/></g><text x="167" y="154" text-anchor="middle" font-size="22">0.8c</text><text x="321" y="154" text-anchor="middle" font-size="22">0.8c</text>',
 '<circle cx="105" cy="112" r="31" fill="#446e9f" stroke="#a2c9f3" stroke-width="1.5"/><path d="M147 112H291" stroke="#54799e" stroke-dasharray="4 7"/><g stroke="#b1d4f6" stroke-width="1.6"><path d="M313 103L347 99L376 112L347 125L313 121Z" fill="#294c70"/><path d="M323 103L313 86L344 100M323 121L313 138L344 124" fill="#365e85"/><circle cx="349" cy="112" r="5" fill="#99c5ed"/><path d="M303 106H288M303 118H288M390 112H435L427 105M435 112L427 119" fill="none"/></g><text x="105" y="165" text-anchor="middle">'+(lang==='zh'?'地球':'Earth')+'</text><text x="345" y="165" text-anchor="middle">'+(lang==='zh'?'飞船':'Spacecraft')+'</text><text x="245" y="43" text-anchor="middle" fill="#c3ddfb" font-size="21">a = const.</text>'
 ];
 return '<div class="diagram"><svg role="img" aria-label="'+t.alt[i]+'" viewBox="0 0 490 190" xmlns="http://www.w3.org/2000/svg"><g fill="#9bb4d2" font-family="Georgia,serif" font-size="17">'+drawings[i]+'</g></svg></div>';
}
function modalContent(){const t=copy[lang];document.getElementById('detail-content').innerHTML=diagram(selected)+`<div class="modal-copy"><span class="eyebrow">0${selected+1}</span><h2 id="detail-title">${t.titles[selected]}</h2><div class="formula">${formula(selected)}</div><p class="pending">${t.pending}</p></div>`;document.getElementById('close').ariaLabel=lang==='zh'?'关闭':'Close'}
function render(){const t=copy[lang];document.documentElement.lang=lang==='zh'?'zh-CN':'en';const toggle=document.getElementById('language');toggle.setAttribute('aria-checked',String(lang==='zh'));toggle.ariaLabel=lang==='zh'?'Switch to English':'切换至中文';document.getElementById('footer-note').textContent=t.footer;
if(location.hash==='#lorentz'){LorentzLesson.render(main,lang);return}
if(location.hash==='#special-relativity'){main.innerHTML=`<section class="section"><a class="back" href="#home">${t.back}</a><div class="section-heading"><div><p class="eyebrow">EXPOSITION · 01</p><h1 tabindex="-1">${t.section}</h1></div></div><a class="notes-banner" href="assets/lorentz.pdf" target="_blank" rel="noopener"><span class="notes-badge">PDF</span><span><strong>${lang==='zh'?'讲义 Notes':'Lecture Notes'}</strong><span class="notes-description">${lang==='zh'?'洛伦兹变换 · 阅读原始推导讲义':'Lorentz Transformation · Read the original derivation'}</span></span><span class="notes-arrow" aria-hidden="true">↗</span></a><div class="grid">${t.titles.map((title,i)=>`<button class="card" data-card="${i}" ${i===0?'':'aria-haspopup="dialog"'}>${diagram(i)}<div class="card-copy"><div class="card-top"><span>0${i+1}</span><span aria-hidden="true">↗</span></div><h2>${title}</h2><div class="formula">${formula(i)}</div></div></button>`).join('')}</div></section>`;main.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.card);if(selected===0){location.hash='lorentz';return}modalContent();dialog.showModal()})}else{main.innerHTML=`<section class="home"><p class="eyebrow">${t.eyebrow}</p><h1 tabindex="-1">${t.title}<br><span>${t.sub}</span></h1><p class="subtitle">${t.intro}</p><nav class="topic-list" aria-label="${lang==='zh'?'物理主题':'Physics topics'}">${t.topics.map((title,i)=>i===0?`<a class="topic active" href="#special-relativity"><span class="number">01</span><span class="topic-title">${title}</span><span class="status">${t.enter}</span></a>`:`<button class="topic" disabled><span class="number">0${i+1}</span><span class="topic-title">${title}</span><span class="status">${t.soon}</span></button>`).join('')}</nav></section>`}if(dialog.open)modalContent()}
document.getElementById('language').onclick=()=>{lang=lang==='en'?'zh':'en';try{localStorage.setItem('physics-language',lang)}catch{}render()};document.getElementById('close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});window.addEventListener('hashchange',()=>{dialog.close();render();main.querySelector('h1').focus();window.scrollTo(0,0)});render();
