/* Equations use native MathML: no network, fonts or rendering service required. */
const LorentzLesson=(()=>{
 let step=0;
 const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
 const m=s=>String(s).split(/(\s+|[=+−(),|<>])/).filter(x=>x.trim()).map(x=>`<${/^[=+−(),|<>]$/.test(x)?'mo':/^\d+$/.test(x)?'mn':'mi'}>${esc(x)}</${/^[=+−(),|<>]$/.test(x)?'mo':/^\d+$/.test(x)?'mn':'mi'}>`).join('');
 const row=s=>`<mrow>${s}</mrow>`,f=(a,b)=>`<mfrac>${row(a)}${row(b)}</mfrac>`,pow=(a,n=2)=>`<msup>${row(a)}<mn>${n}</mn></msup>`,sqrt=a=>`<msqrt>${a}</msqrt>`;
 const matrix=rows=>`<mrow><mo>(</mo><mtable>${rows.map(r=>'<mtr>'+r.map(c=>'<mtd>'+c+'</mtd>').join('')+'</mtr>').join('')}</mtable><mo>)</mo></mrow>`;
 const vec=(a,b)=>matrix([[m(a)],[m(b)]]),M=matrix([[m('A'),m('B')],[m('C'),m('D')]]),V=vec('x','t'),VP=vec('x′','t′');
 const eq=(s)=>`<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">${s}</math>`;
 const arrow='<mo>⇒</mo>';
 const gammaFactor=f(m('1'),sqrt(m('1 −')+f(pow(m('v')),pow(m('c')))));
 const steps=[
 {phase:0,scene:'observers',title:['Set the two observers','先约定两个观察者'],body:['A records an event as (x, t); B records the same event as (x′, t′). Their spatial axes are parallel. B moves at +v relative to A, and A at −v relative to B. The arrows show reciprocal descriptions, not two velocities measured in a third frame.','同一个事件，A 记为 (x, t)，B 记为 (x′, t′)。空间轴平行；B 相对 A 以 +v 运动，A 相对 B 以 −v 运动。图中的箭头表示互相观测的运动，不是第三个参考系中两人的速度。'],equations:[eq(m('t = t′ = 0')),eq(m('x = x′ = 0'))],note:['Choose coincident origins at zero time, identical units, and synchronized clocks within each frame.','令零时刻原点重合，使用相同单位，并在各自参考系内同步时钟。'],page:1},
 {phase:1,scene:'rope',title:['Additivity leads to linearity','从可加性走向线性'],body:['Split a rope into adjacent lengths l₁ and l₂. Its length map is additive. Continuity makes this length map linear. For spacetime intervals, homogeneity of space and time supplies the corresponding additivity; continuity and the common origin then give a linear transformation.','将一根绳子分成相邻的 l₁ 和 l₂ 两段，长度映射应当可加；再加上连续性，就得到线性长度映射。对时空间隔，还需用时空均匀性得到相应的可加性，再结合连续性和共同原点，得到线性变换。'],equations:[eq(m('T(l₁ + l₂) = T(l₁) + T(l₂)'))],note:['The rope is an illustration; homogeneity and continuity are the assumptions used for the full spacetime map.','绳子是直观类比；完整的时空线性映射还用到了均匀性与连续性。'],page:1},
 {phase:1,scene:'event',title:['Write the unknown linear map','写出待定的线性变换'],body:['A flash is one event with two coordinate descriptions. Four coefficients describe the linear map. They depend on v. The coefficient A is not the observer A; likewise for B.','一次闪光是同一个事件，却有两组坐标。用四个随 v 变化的系数表示线性变换。这里的系数 A、B 与观察者 A、B 的名字不同。'],equations:[eq(VP+m('=')+M+V),eq(m('d = det M = AD − BC'))],note:['d ≠ 0: either observer must be able to recover the other’s coordinates.','d ≠ 0：坐标变换必须可逆。'],page:1},
 {phase:1,scene:'event',title:['Keep the inverse at hand','同时写下逆变换'],body:['Invert the 2 × 2 matrix. We will use it to follow A’s origin from B’s description, just as the forward map follows B’s origin from A’s description.','将 2 × 2 矩阵求逆。接下来，正变换用来追踪 B 的原点，逆变换则用来追踪 A 的原点。'],equations:[eq(V+m('=')+f(m('1'),m('d'))+matrix([[m('D'),m('−B')],[m('−C'),m('A')]])+VP)],page:1},
 {phase:2,scene:'originB',title:['Follow B’s origin','追踪 B 的原点'],body:['B is always at x′ = 0 in B’s own frame. In A’s frame that same origin follows x = vt. Substitute both facts into the first row of the transformation.','B 在自己的参考系中始终位于 x′ = 0；在 A 系中，这个原点沿 x = vt 运动。将这两点代入正变换的第一行。'],equations:[eq(m('0 = Ax + Bt = (Av + B)t')),eq(m('B = −Av'))],page:1},
 {phase:2,scene:'originA',title:['Follow A’s origin','再追踪 A 的原点'],body:['At A’s origin, x = 0 and x′ = −vt′. The first row of the inverse gives the second expression for B. Comparing it with the previous step makes the two diagonal coefficients equal.','A 的原点满足 x = 0、x′ = −vt′。代入逆变换第一行，得到 B 的另一个表达式；与上一步比较，两个对角系数相等。'],equations:[eq(m('0 = Dx′ − Bt′ = (−Dv − B)t′')),eq(m('B = −Dv = −Av')+arrow+m('A = D'))],note:['For v ≠ 0. The v = 0 case follows continuously with M(0) = I.','这里先取 v ≠ 0；v = 0 的情形由连续性及 M(0) = I 得到。'],page:1},
 {phase:3,scene:'clocks',title:['Compare the two clock experiments','比较两次时钟实验'],body:['First compare two ticks at A’s fixed position: Δx = 0. Then compare two ticks at B’s fixed position: Δx′ = 0, using the inverse map. These are two different pairs of events.','先比较 A 的钟在固定位置的两次滴答，此时 Δx = 0；再用逆变换比较 B 的钟在固定位置的两次滴答，此时 Δx′ = 0。这是两组不同的事件。'],equations:[eq(m('Δt′ = D Δt')),eq(m('Δt =')+f(m('A'),m('d'))+m('Δt′'))],note:['Do not substitute one clock relation into the other as though the intervals came from the same event pair.','不能把这两式当作同一对事件的时间间隔，直接互相代入。'],page:2},
 {phase:3,scene:'clocks',title:['Symmetry fixes the determinant','用对称性确定行列式'],body:['The relativity principle and spatial isotropy make the clock-rate factor the same when the observers exchange roles. Thus D = A/d. Since A = D and the map is connected to the identity, d = 1.','相对性原理与空间各向同性要求：交换两位观察者后，钟速因子相同。因此 D = A/d；又因为 A = D，且变换与恒等变换连续相连，得到 d = 1。'],equations:[eq(m('D =')+f(m('A'),m('d'))+m(', A = D')+arrow+m('d = 1'))],page:2},
 {phase:3,scene:'matrix',title:['Only one coefficient remains','只剩一个待定系数'],body:['Use d = AD − BC = 1 together with D = A and B = −Av. This expresses C in terms of A.','将 D = A、B = −Av 代入 d = AD − BC = 1，就能用 A 表示 C。'],equations:[eq(m('AD − BC =')+pow(m('A'))+m('+ AvC = 1')),eq(m('C =')+f(m('1 −')+pow(m('A')),m('Av'))),eq(VP+m('=')+matrix([[m('A'),m('−Av')],[f(m('1 −')+pow(m('A')),m('Av')),m('A')]])+V)],page:2},
 {phase:4,scene:'light',title:['Send a light ray','让一束光出发'],body:['A light ray leaves the common origin in the positive direction. Both observers measure speed c, so its trajectory obeys x = ct and x′ = ct′. Substitute these into the two rows.','一束光从共同原点沿正方向传播。两位观察者都测得光速 c，因此光线满足 x = ct、x′ = ct′。将它们代入变换的两行。'],equations:[eq(m('ct′ = A(c − v)t')),eq(m('t′ = (Cc + A)t'))],page:2},
 {phase:4,scene:'light',title:['Eliminate the transformed time','消去变换后的时间'],body:['Multiply the second expression by c and compare with the first. The Ac terms cancel, leaving a direct relation between C and A.','将第二式乘以 c，与第一式比较。两边的 Ac 项消去，得到 C 与 A 的直接关系。'],equations:[eq(m('c(Cc + A) = A(c − v)')),eq(m('C')+pow(m('c'))+m('= −Av'))],page:2},
 {phase:4,scene:'solve',title:['Solve for the scale factor','求出比例因子'],body:['Insert C = (1 − A²)/(Av). Multiply through by Av and collect the terms containing A².','代入 C = (1 − A²)/(Av)，两边乘以 Av，再合并含 A² 的项。'],equations:[eq(f(m('1 −')+pow(m('A')),m('Av'))+pow(m('c'))+m('= −Av')),eq(m('(1 −')+pow(m('A'))+m(')')+pow(m('c'))+m('= −')+pow(m('A'))+pow(m('v'))),eq(pow(m('A'))+m('(')+pow(m('c'))+m('−')+pow(m('v'))+m(') =')+pow(m('c')))],page:2},
 {phase:4,scene:'solve',title:['Choose the continuous positive root','选择连续的正根'],body:['At v = 0 the transformation is the identity, so A(0) = 1. Choose the positive root connected to that limit and call it γ. The remaining coefficients now follow.','当 v = 0 时，变换为恒等变换，A(0) = 1。因此选择与它连续相连的正根，并记为 γ；其余系数随之确定。'],equations:[eq(m('A =')+gammaFactor+m('≡ γ')),eq(m('D = γ, B = −γv, C = −')+f(m('γv'),pow(m('c')))),eq(m('|v| < c'))],page:2},
 {phase:5,scene:'final',title:['The Lorentz transformation','得到洛伦兹变换'],body:['These coordinates describe the same event. With B moving at +v relative to A, the forward transformation carries minus signs in its off-diagonal entries.','这两组坐标描述同一个事件。按 B 相对 A 以 +v 运动的约定，正变换的两个非对角项带负号。'],equations:[eq(VP+m('= γ')+matrix([[m('1'),m('−v')],[m('−')+f(m('v'),pow(m('c'))),m('1')]])+V),eq(m('x′ = γ(x − vt)')),eq(m('t′ = γ(t −')+f(m('vx'),pow(m('c')))+m(')'))],page:2},
 {phase:5,scene:'final',title:['Exchange the observers','交换观察者：逆变换'],body:['Reverse the relative velocity, v → −v. This gives the inverse transformation and completes the chain from linearity and symmetry to light-speed invariance.','交换观察者相当于令 v → −v，即得到逆变换。从线性、对称性到光速不变，推导至此完成。'],equations:[eq(V+m('= γ')+matrix([[m('1'),m('v')],[f(m('v'),pow(m('c'))),m('1')]])+VP),eq(m('x = γ(x′ + vt′)')),eq(m('t = γ(t′ +')+f(m('vx′'),pow(m('c')))+m(')'))],note:['At v = 0, γ = 1 and both maps reduce to the identity.','当 v = 0 时，γ = 1，正、逆变换均退化为恒等变换。'],page:2}
 ];
 const tr=(a,l)=>a[l==='zh'?1:0];
 const phases=[['Setup','约定'],['Linearity','线性'],['Origins','原点'],['Clock symmetry','时钟对称'],['Light','光速不变'],['Result','结论']];
 function person(x,y,color,label){return `<g transform="translate(${x} ${y})" stroke="${color}" fill="none" stroke-width="3" stroke-linecap="round"><circle cy="-42" r="11"/><path d="M0 -31V4M0 -22L-19 -9M0 -22L19 -9M0 4L-17 27M0 4L17 27"/><text y="55" text-anchor="middle" stroke="none" fill="${color}" font-size="18">${label}</text></g>`}
 function scene(l){const s=steps[step].scene,zh=l==='zh';let content='',caption='';
 if(s==='rope'){content=`<path class="draw" d="M65 145H230" stroke="#71cfff" stroke-width="6"/><path class="draw" d="M230 145H405" stroke="#ffd18a" stroke-width="6"/><path d="M65 130V160M230 130V160M405 130V160" stroke="#ccd8ec"/><text x="140" y="122">l₁</text><text x="308" y="122">l₂</text><path d="M65 185V199H405V185" stroke="#a6b4ce" fill="none"/><text x="235" y="233" text-anchor="middle">l₁ + l₂</text>`;caption=zh?'相邻的两段，合成同一根绳子。':'Two adjacent pieces form one rope.'}
 else if(s==='clocks'){content=person(115,150,'#71cfff','A')+person(355,150,'#ffd18a','B')+`<g fill="none" stroke-width="2"><circle cx="115" cy="58" r="24" stroke="#71cfff"/><path class="clock-hand" d="M115 58V42M115 58L128 64" stroke="#71cfff"/><circle cx="355" cy="58" r="24" stroke="#ffd18a"/><path class="clock-hand" d="M355 58V42M355 58L368 64" stroke="#ffd18a"/></g><text x="115" y="245" text-anchor="middle" fill="#71cfff">Δx = 0</text><text x="355" y="245" text-anchor="middle" fill="#ffd18a">Δx′ = 0</text>`;caption=zh?'两只钟，两组不同的事件。':'Two clocks. Two different pairs of events.'}
 else if(s==='matrix'||s==='solve'){content=`<text x="235" y="120" text-anchor="middle" fill="#9ae1bd" font-size="42">${s==='matrix'?'d = 1':'A = γ'}</text><path d="M110 158H360" stroke="#4e6b87"/><text x="235" y="205" text-anchor="middle" font-size="23">${s==='matrix'?'A = D · B = −Av':'γ ≥ 1'}</text>`;caption=zh?'每一步都减少一个未知量。':'Each constraint removes an unknown.'}
 else{content=person(120,145,'#71cfff','A · (x, t)')+person(350,145,'#ffd18a','B · (x′, t′)');content+=`<g stroke-width="2" fill="none"><path d="M92 92H40L49 86M40 92L49 98" stroke="#71cfff"/><path d="M378 92H430L421 86M430 92L421 98" stroke="#ffd18a"/></g><text x="61" y="74" fill="#71cfff">−v</text><text x="393" y="74" fill="#ffd18a">+v</text>`;
 if(s==='light'){content+=`<path d="M62 236H414" stroke="#80dfb2" stroke-width="2"/><circle class="photon" cx="70" cy="236" r="5" fill="#bcffcd"/><text x="235" y="268" text-anchor="middle" fill="#9ae1bd">x = ct · x′ = ct′</text>`;caption=zh?'同一束光，两位观察者都测得 c。':'One light ray, measured at c in both frames.'}
 else if(s==='originB'){content+=`<text x="235" y="246" text-anchor="middle" fill="#ffd18a">x′ = 0 · x = vt</text>`;caption=zh?'选定 B 的原点，代入正变换。':'Follow B’s origin through the forward map.'}
 else if(s==='originA'){content+=`<text x="235" y="246" text-anchor="middle" fill="#71cfff">x = 0 · x′ = −vt′</text>`;caption=zh?'选定 A 的原点，代入逆变换。':'Follow A’s origin through the inverse map.'}
 else if(s==='event'){content+=`<circle class="flash" cx="235" cy="80" r="7" fill="#a5f3c4"/><path d="M230 91L160 205M240 91L310 205" stroke="#658576" stroke-dasharray="4 6"/>`;caption=zh?'同一次闪光，两个坐标描述。':'One flash, two coordinate descriptions.'}
 else{content+=`<text x="235" y="246" text-anchor="middle" fill="#a5f3c4">${s==='final'?'v ↔ −v':'t = t′ = 0'}</text>`;caption=zh?'蓝色：观察者 A；金色：观察者 B。':'Blue: observer A. Gold: observer B.'}}
 return `<svg viewBox="0 0 470 290" role="img" aria-label="${caption}" xmlns="http://www.w3.org/2000/svg"><g fill="#dce8f9" font-family="Georgia,serif" font-size="22">${content}</g></svg><p class="scene-caption">${caption}</p>`}
 function block(s,i,l){return `<article class="proof-block ${i===step?'current':''}" data-step="${i}" tabindex="-1"><div class="block-meta"><span>${String(i+1).padStart(2,'0')} / ${steps.length}</span><span>PDF · ${s.page}</span></div><h2>${tr(s.title,l)}</h2><p>${tr(s.body,l)}</p><div class="proof-equations">${s.equations.join('')}</div>${s.note?'<p class="proof-note">'+tr(s.note,l)+'</p>':''}</article>`}
 function render(main,l){const zh=l==='zh';main.innerHTML=`<section class="lesson"><a class="back" href="#special-relativity">${zh?'← 狭义相对论':'← Special Relativity'}</a><div class="lesson-heading"><div><p class="eyebrow">01 · LORENTZ TRANSFORMATION</p><h1 tabindex="-1">${zh?'一步一步，变换时空':'Transforming space and time'}</h1></div><a class="source-link" href="assets/lorentz.pdf" target="_blank" rel="noopener"><span class="source-pdf">PDF</span> ${zh?'阅读原始讲义 ↗':'Read source notes ↗'}</a></div><ol class="proof-phases">${phases.map((p,i)=>`<li class="${i===steps[step].phase?'active':i<steps[step].phase?'passed':''}">${tr(p,l)}</li>`).join('')}</ol><div class="lesson-layout"><aside class="scene-panel"><button type="button" id="proof-scene" aria-label="${zh?'显示下一步证明':'Reveal next proof step'}" ${step===steps.length-1?'disabled':''}>${scene(l)}</button><div class="lesson-controls"><button id="proof-prev" ${step===0?'disabled':''}>${zh?'上一步':'Back'}</button><button id="proof-next" ${step===steps.length-1?'disabled':''}>${step===steps.length-1?(zh?'推导完成 ✓':'Complete ✓'):(zh?'下一步 →':'Next step →')}</button><button id="proof-reset">${zh?'重看':'Restart'}</button></div><p class="control-hint">${zh?'点击画面或“下一步”，展开一个证明块。<br>也可使用 → / 空格；← 返回。':'Click the scene or Next step to reveal one block.<br>Use → / Space to advance; ← to go back.'}</p><div class="proof-progress" role="progressbar" aria-label="${zh?'推导进度':'Proof progress'}" aria-valuemin="1" aria-valuemax="${steps.length}" aria-valuenow="${step+1}"><span style="width:${100*(step+1)/steps.length}%"></span></div><p class="progress-text" aria-live="polite">${step+1} / ${steps.length}</p></aside><div class="proof-feed" aria-label="${zh?'逐步推导':'Step-by-step derivation'}">${steps.slice(0,step+1).map((s,i)=>block(s,i,l)).join('')}</div></div></section>`;
 const go=n=>{const focusId=document.activeElement?.id;step=Math.max(0,Math.min(steps.length-1,n));render(main,l);if(focusId&&document.getElementById(focusId)&&!document.getElementById(focusId).disabled)document.getElementById(focusId).focus({preventScroll:true});const feed=main.querySelector('.proof-feed');feed.scrollTop=feed.scrollHeight;};main.querySelector('#proof-next').onclick=()=>go(step+1);main.querySelector('#proof-scene').onclick=()=>go(step+1);main.querySelector('#proof-prev').onclick=()=>go(step-1);main.querySelector('#proof-reset').onclick=()=>go(0);
 const feed=main.querySelector('.proof-feed');feed.scrollTop=feed.scrollHeight;
 }
 document.addEventListener('keydown',e=>{if(location.hash!=='#lorentz'||e.altKey||e.ctrlKey||e.metaKey||e.target.closest('button,a,input,select,textarea'))return;const id=e.key==='ArrowLeft'?'proof-prev':(e.key==='ArrowRight'||e.key===' ')?'proof-next':null;if(id){e.preventDefault();document.getElementById(id)?.click()}});
 return {render};
})();
